// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttemptStartRuntime(arg1) {
  return window['go']['main']['App']['AttemptStartRuntime'](arg1);
}

export function CheckImageExists(arg1) {
  return window['go']['main']['App']['CheckImageExists'](arg1);
}

export function CheckMultipleImagesExist(arg1) {
  return window['go']['main']['App']['CheckMultipleImagesExist'](arg1);
}

export function CheckStartingServicesProgress() {
  return window['go']['main']['App']['CheckStartingServicesProgress']();
}

export function GetAllDependencyStatuses() {
  return window['go']['main']['App']['GetAllDependencyStatuses']();
}

export function GetAllRunningServices() {
  return window['go']['main']['App']['GetAllRunningServices']();
}

export function GetAllServiceDetails() {
  return window['go']['main']['App']['GetAllServiceDetails']();
}

export function GetAllServicesWithStatusAndDependencies() {
  return window['go']['main']['App']['GetAllServicesWithStatusAndDependencies']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetCurrentRuntime() {
  return window['go']['main']['App']['GetCurrentRuntime']();
}

export function GetCustomDockerPath() {
  return window['go']['main']['App']['GetCustomDockerPath']();
}

export function GetCustomPodmanPath() {
  return window['go']['main']['App']['GetCustomPodmanPath']();
}

export function GetImageInfo(arg1) {
  return window['go']['main']['App']['GetImageInfo'](arg1);
}

export function GetImagePullProgress(arg1) {
  return window['go']['main']['App']['GetImagePullProgress'](arg1);
}

export function GetMultipleImageInfo(arg1) {
  return window['go']['main']['App']['GetMultipleImageInfo'](arg1);
}

export function GetMultipleServiceStatuses(arg1) {
  return window['go']['main']['App']['GetMultipleServiceStatuses'](arg1);
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetServiceConnectionInfo(arg1) {
  return window['go']['main']['App']['GetServiceConnectionInfo'](arg1);
}

export function GetServiceLogs(arg1, arg2) {
  return window['go']['main']['App']['GetServiceLogs'](arg1, arg2);
}

export function GetServiceStatus(arg1) {
  return window['go']['main']['App']['GetServiceStatus'](arg1);
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function OpenServiceInBrowser(arg1) {
  return window['go']['main']['App']['OpenServiceInBrowser'](arg1);
}

export function RefreshStatusFromContainers() {
  return window['go']['main']['App']['RefreshStatusFromContainers']();
}

export function ReinitializeRuntime() {
  return window['go']['main']['App']['ReinitializeRuntime']();
}

export function SetCustomDockerPath(arg1) {
  return window['go']['main']['App']['SetCustomDockerPath'](arg1);
}

export function SetCustomPodmanPath(arg1) {
  return window['go']['main']['App']['SetCustomPodmanPath'](arg1);
}

export function StartImagePull(arg1) {
  return window['go']['main']['App']['StartImagePull'](arg1);
}

export function StartLogStream(arg1) {
  return window['go']['main']['App']['StartLogStream'](arg1);
}

export function StartService(arg1, arg2) {
  return window['go']['main']['App']['StartService'](arg1, arg2);
}

export function StartServiceWithStatusUpdate(arg1, arg2) {
  return window['go']['main']['App']['StartServiceWithStatusUpdate'](arg1, arg2);
}

export function StopAllServices() {
  return window['go']['main']['App']['StopAllServices']();
}

export function StopAllServicesWithStatusUpdate() {
  return window['go']['main']['App']['StopAllServicesWithStatusUpdate']();
}

export function StopImagePull(arg1) {
  return window['go']['main']['App']['StopImagePull'](arg1);
}

export function StopLogStream(arg1) {
  return window['go']['main']['App']['StopLogStream'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopServiceWithStatusUpdate(arg1) {
  return window['go']['main']['App']['StopServiceWithStatusUpdate'](arg1);
}

export function WaitForRuntimeReady(arg1, arg2) {
  return window['go']['main']['App']['WaitForRuntimeReady'](arg1, arg2);
}
