services:
  activemq:
    volumes:
      - "./data/activemq/persist:/var/lib/artemis-instance"
  cassandra-server:
    volumes:
      - "./data/cassandra/persist:/var/lib/cassandra"
  clickhouse-server:
    volumes:
      - "./data/clickhouse/persist:/var/lib/clickhouse"
  cockroachdb:
    volumes:
      - "./data/cockroachdb/persist:/cockroach/cockroach-data"
  dagster:
    volumes:
      - "./data/dagster/persist:/opt/dagster/dagster_home/"
  druid:
    volumes:
      - "./data/druid/persist/router_var:/opt/druid/var"
  druid-broker:
    volumes:
      - "./data/druid/persist/broker_var:/opt/druid/var"
  druid-coordinator:
    volumes:
      - "./data/druid/persist/shared:/opt/shared"
      - "./data/druid/persist/coordinator_var:/opt/druid/var"
  druid-historical:
    volumes:
      - "./data/druid/persist/shared:/opt/shared"
      - "./data/druid/persist/historical_var:/opt/druid/var"
  druid-middlemanager:
    volumes:
      - "./data/druid/persist/shared:/opt/shared"
      - "./data/druid/persist/middle_var:/opt/druid/var"
  elasticsearch:
    volumes:
      - "./data/elasticsearch/persist:/usr/share/elasticsearch/data:Z"
  feast:
    volumes:
      - "./data/feast/persist:/feast-registry"
  flight-sql:
    volumes:
      - "./data/flight-sql/persist:/opt/data"
  grafana:
    volumes:
      - "./data/grafana/persist:/var/lib/grafana"
  influxdb:
    volumes:
      - "./data/influxdb/persist:/var/lib/influxdb2"
  jaeger:
    volumes:
      - "./data/jaeger/persist:/badger"
  jupyter:
    volumes:
      - "./data/jupyter/persist:/home/jovyan/work"
  kafka-server:
    volumes:
      - "./data/kafka/persist/data:/var/lib/kafka/data"
      - "./data/kafka/persist/etc:/etc/kafka"
  lakekeeper-jupyter:
    volumes:
      - "./data/lakekeeper-jupyter/persist:/home/jovyan/work"
  loki:
    volumes:
      - "./data/loki/persist:/loki"
  mage-ai:
    volumes:
      - "./data/mage-ai/persist:/home/src/"
  mariadb:
    volumes:
      - "./data/mariadb/persist:/var/lib/mysql:Z"
  marquez-server:
    volumes:
      - "./data/marquez/persist:/opt/marquez"
  milvus:
    volumes:
      - "./data/milvus/persist:/var/lib/milvus"
  minio:
    volumes:
      - "./data/minio/persist:/data"
  mlflow:
    volumes:
      - "./data/mlflow/persist:/mlflow"
  mongodb-server:
    volumes:
      - "./data/mongodb/persist:/data/db"
  mssql:
    volumes:
      - "./data/mssql/persist:/var/opt/mssql/data"
  mysql-server:
    volumes:
      - "./data/mysql/persist:/var/lib/mysql"
  nats:
    volumes:
      - "./data/nats/persist:/data"
  neo4j:
    volumes:
      - "./data/neo4j/persist:/data"
  openmetadata:
    volumes:
      - "./data/openmetadata-ingestion/ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs"
      - "./data/openmetadata-ingestion/ingestion-volume-dags:/opt/airflow/dags"
      - "./data/openmetadata-ingestion/ingestion-volume-tmp:/tmp"
  opensearch:
    volumes:
      - "./data/opensearch/persist:/usr/share/opensearch/data"
  polaris:
    volumes:
      - "./data/polaris/persist/credentials:/tmp/credentials"
  postgres-server:
    volumes:
      - "./data/postgres/persist:/data/postgres"
  prefect-server:
    volumes:
      - "./data/prefect/persist:/root/.prefect"
  prometheus:
    volumes:
      - "./data/prometheus/persist:/prometheus"
  pulsar:
    volumes:
      - "./data/pulsar/persist/data:/pulsar/data"
  qdrant:
    volumes:
      - "./data/qdrant/persist:/qdrant/storage"
  rabbitmq:
    volumes:
      - "./data/rabbitmq/persist:/var/lib/rabbitmq"
  ray:
    volumes:
      - "./data/ray/persist:/tmp/ray"
  redis:
    volumes:
      - "./data/redis/persist:/data"
  solace-server:
    volumes:
      - "./data/solace/persist:/var/lib/solace"
  sqlite:
    volumes:
      - "./data/sqlite/persist:/opt/data"
  temporal:
    volumes:
      - "./data/temporal/persist:/opt/data/db"
  timescaledb:
    volumes:
      - "./data/timescaledb/persist:/var/lib/postgresql/data"
  unitycatalog:
    volumes:
      - "./data/unitycatalog/persist:/opt/app/etc"
  vault:
    volumes:
      - "./data/vault/persist:/vault/file"
  weaviate:
    volumes:
      - "./data/weaviate/persist:/var/lib/weaviate"
