#!/bin/bash

set -euo pipefail

# wait for MSSQL server to start
export STATUS=1
i=0

while [[ $STATUS -ne 0 ]] && [[ $i -lt 30 ]]; do
  i=$i+1
  /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $SA_PASSWORD -Q 'SELECT @@VERSION' >> /dev/null
  STATUS=$?
done

if [ $STATUS -ne 0 ]; then 
  echo "Error: MSSQL SERVER took more than thirty seconds to start up."
  exit 1
fi
